# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='cont_num',
            field=models.IntegerField(null=True),
        ),
    ]
