# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 17:41
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20180114_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
