# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20180114_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
