# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20180114_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
